### ISSUE TITLE
Feat: 로그인 정보 저장 기능 추가 및 페이지 연결

### ISSUE THREAD

**Issue by Choi-Jiwon-38** [TEAM-LINRING/LINRING-FRONT-FLUTTER#49]
**✍ Description**
 로그인의 Response로 받는 사용자 정보를 Flutter 내부에서 저장 및 사용해야 합니다. 또한, 저장된 로그인 정보를 바탕으로 사용자 로그인 유지 기능, API 호출 기능 등을 수정합니다.

**📋 To do**
- [x] 로그인 Response로 받는 사용자 정보를 Flutter 내부에 저장
- [x] 로그인 상태 유지 기능 추가
- [x] 다른 페이지의 API 호출 방식 변경

**➕ Etc.**
`FlutterSecureStroage`를 사용하여 구현할 수 있을 것으로 보입니다.

**Comment by Choi-Jiwon-38** [comment]
현재 아래와 같은 에러 상황이 발생하였습니다.
별도의 이슈는 생성하지 않고 해결 과정은 comment로 잇도록 하겠습니다.

```bash
Internal Server Error: /api/accounts/register/
Traceback (most recent call last):
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/allauth/account/utils.py", line 313, in send_email_confirmation
    email_address = EmailAddress.objects.get_for_user(user, email)
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/allauth/account/managers.py", line 54, in get_for_user
    ret = self.get(user=user, email__iexact=email)
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
allauth.account.models.EmailAddress.DoesNotExist: EmailAddress matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/dj_rest_auth/registration/views.py", line 42, in dispatch
    return super().dispatch(*args, **kwargs)
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/dj_rest_auth/registration/views.py", line 64, in create
    user = self.perform_create(serializer)
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/dj_rest_auth/registration/views.py", line 90, in perform_create
    complete_signup(
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/allauth/account/utils.py", line 186, in complete_signup
    return perform_login(
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/allauth/account/utils.py", line 168, in perform_login
    response = adapter.pre_login(request, user, **hook_kwargs)
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/allauth/account/adapter.py", line 412, in pre_login
    send_email_confirmation(request, user, signup=signup, email=email)
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/allauth/account/utils.py", line 324, in send_email_confirmation
    email_address = EmailAddress.objects.add_email(
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/allauth/account/managers.py", line 24, in add_email
    email_address.send_confirmation(request, signup=signup)
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/allauth/account/models.py", line 60, in send_confirmation
    confirmation.send(request, signup=signup)
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/allauth/account/models.py", line 168, in send
    get_adapter(request).send_confirmation_mail(request, self, signup)
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/allauth/account/adapter.py", line 549, in send_confirmation_mail
    self.send_mail(email_template, emailconfirmation.email_address.email, ctx)
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/allauth/account/adapter.py", line 140, in send_mail
    msg.send()
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/django/core/mail/message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 127, in send_messages
    new_conn_created = self.open()
  File "/Users/choijiwon/Desktop/GitHub-Desktop/무제/LINRING-API/venv/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 92, in open
    self.connection.starttls(context=self.ssl_context)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 790, in starttls
    self.sock = context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
[29/Oct/2023 02:47:00] "POST /api/accounts/register/ HTTP/1.1" 500 206313
```

**Comment by Choi-Jiwon-38** [comment]
위 에러는 venv 내부 ssl 설정이 되어 있지 않아서 발생한 문제였습니다.
